version: '3.8'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=super_set
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
    restart: always
volumes:
  db-data: {}
