# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
postgres-jdbc-driver = "42.7.3"
spring-boot = "3.2.5"
spring-dependency-management = "1.1.4"

[libraries]
pg-driver = {module="org.postgresql:postgresql", version.ref="postgres-jdbc-driver"}
spring-boot-devtools = {module="org.springframework.boot:spring-boot-devtools", version.ref="spring-boot"}
spring-boot-starter-data-jpa = {module="org.springframework.boot:spring-boot-starter-data-jpa", version.ref="spring-boot"}
spring-boot-starter-test = {module="org.springframework.boot:spring-boot-starter-test", version.ref="spring-boot"}
spring-boot-starter-validation = {module="org.springframework.boot:spring-boot-starter-validation", version.ref="spring-boot"}
spring-boot-starter-web = {module="org.springframework.boot:spring-boot-starter-web", version.ref="spring-boot"}

[plugins]
spring-boot = {id="org.springframework.boot", version.ref="spring-boot"}
spring-dependency-management = {id="io.spring.dependency-management", version.ref="spring-dependency-management"}
